services:
  - type: web
    name: trpc-websockets
    env: node
    plan: free
    region: frankfurt
    buildCommand: yarn --prod=false &&
      yarn build
    startCommand: yarn start
    healthCheckPath: /api/trpc/healthz
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false

      - fromGroup: trpc-websockets
